// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxT1wL0UI7uELGcvbR9HCRfsfDtkBcTJY',
    appId: '1:172453953806:web:3f04d48ae036c94463175f',
    messagingSenderId: '172453953806',
    projectId: 'login1-6f3b2',
    authDomain: 'login1-6f3b2.firebaseapp.com',
    storageBucket: 'login1-6f3b2.firebasestorage.app',
    measurementId: 'G-C81GHCXTHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7fd3I5r6bE6br2enAtMs43c7cReVa8k8',
    appId: '1:172453953806:android:88be8dba7ae14b1a63175f',
    messagingSenderId: '172453953806',
    projectId: 'login1-6f3b2',
    storageBucket: 'login1-6f3b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVVYM9B7Wi31n29taf0-UJqE7bWd7q1QM',
    appId: '1:172453953806:ios:2a74b2d97978cd9263175f',
    messagingSenderId: '172453953806',
    projectId: 'login1-6f3b2',
    storageBucket: 'login1-6f3b2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVVYM9B7Wi31n29taf0-UJqE7bWd7q1QM',
    appId: '1:172453953806:ios:2a74b2d97978cd9263175f',
    messagingSenderId: '172453953806',
    projectId: 'login1-6f3b2',
    storageBucket: 'login1-6f3b2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxT1wL0UI7uELGcvbR9HCRfsfDtkBcTJY',
    appId: '1:172453953806:web:e6104c6edb8d2f0b63175f',
    messagingSenderId: '172453953806',
    projectId: 'login1-6f3b2',
    authDomain: 'login1-6f3b2.firebaseapp.com',
    storageBucket: 'login1-6f3b2.firebasestorage.app',
    measurementId: 'G-SMXDBK4BXW',
  );
}
